version: 0.2

phases:
  install:
    commands:
      - npm install -g pnpm
      - pnpm --version
      - pnpm install

  build:
    commands:
      - echo "Backend scheduler: NYI"
        # cd apps/backend/scheduler
        # pnpm build
        # cd ../../..

      - echo "Building backend: timesheets"
      - cd apps/backend/timesheets
      - pnpm build
      - cd ../../..

      - echo "Frontend scheduler: NYI"
        # cd apps/frontend/scheduler
        # pnpm build
        # cd ../../..

      - echo "Building frontend: timesheets"
      - cd apps/frontend/timesheets
      - pnpm build
      - cd ../../..

      - echo "Synthesizing CDK"
      - pnpm exec cdk synth --output dist/cdk

artifacts:
  files:
    - '**/*'
  base-directory: dist/cdk
