version: 0.2

phases:
  install:
    commands:
      - npm install -g pnpm
      - pnpm --version

      # Install Node 20 on Ubuntu CodeBuild image
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs

      # Force PATH to use Node 20 instead of preinstalled Node 18
      - export PATH=/usr/bin:$PATH
      - hash -r

      - node --version

      # Install CDK CLI globally
      - npm install -g aws-cdk

      # install root workspace deps
      - pnpm install

  build:
    commands:
      - echo "Backend scheduler - NYI"
      - echo "Building backend - timesheets"
      - cd apps/backend/timesheets
      - pnpm build
      - cd ../../..

      - echo "Frontend scheduler - NYI"
      - echo "Building frontend - timesheets"
      - cd apps/frontend/timesheets
      - pnpm build
      - cd ../../..

      - echo "Synthesizing CDK"
      - cd infra
      - pnpm install
      - pnpm exec cdk synth --output dist/cdk
      - cd ..

      - echo "Copying frontend build into CDK output for deploy stage"
      - mkdir -p infra/dist/cdk/frontend
      - cp -r apps/frontend/timesheets/dist/* infra/dist/cdk/frontend/

artifacts:
  files:
    - "**/*"
  base-directory: infra/dist/cdk
