version: 0.2

phases:
  install:
    commands:
      - npm install -g pnpm
      - pnpm --version
      - pnpm install

  build:
    commands:
      - echo "Running backend tests (timesheets)…"
      - cd apps/backend/timesheets
      - pnpm test
      - cd ../../..

      - echo "Running frontend tests (timesheets)…"
      - cd apps/frontend/timesheets
      - pnpm test
      - cd ../../..

artifacts:
  files:
    - '**/*'
  base-directory: .
